using System;
using System.Collections.Generic;
using System.Text;

using GenHTTP.Api.Infrastructure;
using GenHTTP.Api.Protocol;

namespace GenHTTP.Api.Modules
{
    
    /// <summary>
    /// A builder which will provide an <see cref="IContentProvider"/>.
    /// </summary>
    public interface IContentBuilder : IBuilder<IContentProvider>
    {

        /// <summary>
        /// Register a modification that will be applied to every
        /// response generated by the resulting content provider.
        /// </summary>
        /// <param name="modification">The modification to be applied</param>
        IContentBuilder Modify(ResponseModification modification);

    }

}
