using System.Reflection;

namespace GenHTTP.Modules.Reflection.Operations;

public sealed class Operation
{

    #region Get-/Setters

    /// <summary>
    /// The .NET method to be executed to retrieve a result.
    /// </summary>
    public MethodInfo Method { get; }

    /// <summary>
    /// Information about the endpoint provided by this operation.
    /// </summary>
    public OperationPath Path { get; }

    /// <summary>
    /// The arguments expected by this operation.
    /// </summary>
    public IReadOnlyDictionary<string, OperationArgument> Arguments { get; }

    /// <summary>
    /// The interceptors to be executed for this operation.
    /// </summary>
    public IReadOnlyList<IOperationInterceptor> Interceptors { get; }

    /// <summary>
    /// The result generated by this operation.
    /// </summary>
    public OperationResult Result { get; }

    #endregion

    #region Initialization

    public Operation(MethodInfo method, OperationPath path, OperationResult result, IReadOnlyDictionary<string, OperationArgument> arguments, IReadOnlyList<IOperationInterceptor> interceptors)
    {
        Method = method;
        Path = path;
        Result = result;
        Arguments = arguments;
        Interceptors = interceptors;
    }

    #endregion

}
