using System.Reflection;

namespace GenHTTP.Modules.Reflection.Operations;

public sealed class Operation
{

    #region Get-/Setters

    /// <summary>
    /// The .NET method to be executed to retrieve a result.
    /// </summary>
    public MethodInfo Method { get; }

    /// <summary>
    /// If available, the delegate to be executed at runtime
    /// to retrieve a result.
    /// </summary>
    public Delegate? Delegate { get; }

    /// <summary>
    /// Specifies the way the method should be executed.
    /// </summary>
    public ExecutionSettings ExecutionSettings { get; }

    /// <summary>
    /// The configuration of this method.
    /// </summary>
    public IMethodConfiguration Configuration { get; }

    /// <summary>
    /// Information about the endpoint provided by this operation.
    /// </summary>
    public OperationPath Path { get; }

    /// <summary>
    /// The arguments expected by this operation.
    /// </summary>
    public IReadOnlyDictionary<string, OperationArgument> Arguments { get; }

    /// <summary>
    /// The interceptors to be executed for this operation.
    /// </summary>
    public IReadOnlyList<IOperationInterceptor> Interceptors { get; }

    /// <summary>
    /// The result generated by this operation.
    /// </summary>
    public OperationResult Result { get; }

    #endregion

    #region Initialization

    public Operation(MethodInfo method, Delegate? del, ExecutionSettings executionSettings, IMethodConfiguration configuration, OperationPath path, OperationResult result, IReadOnlyDictionary<string, OperationArgument> arguments, IReadOnlyList<IOperationInterceptor> interceptors)
    {
        Method = method;
        Delegate = del;
        ExecutionSettings = executionSettings;
        Configuration = configuration;
        Path = path;
        Result = result;
        Arguments = arguments;
        Interceptors = interceptors;
    }

    #endregion

}
