using GenHTTP.Modules.Minification.Concern;

namespace GenHTTP.Modules.Minification
{

    /// <summary>
    /// Adds a concern that will anaylze the content generated by your
    /// handlers and will minify this content if applicable.
    /// </summary>
    /// <remarks>
    /// As minification trades file size for CPU cycles, it is recommended
    /// that you combine this concern with a server side cache to get
    /// the best of both worlds. Nevertheless this concern can be
    /// used to minify responses on the fly without caching anything.
    /// </remarks>
    public static class Minify
    {

        /// <summary>
        /// Creates a concern that will minify typical web assets (JS, CSS, HTML).
        /// </summary>
        /// <returns>The configured concern builder</returns>
        public static MinifyBuilder Default() => Empty().AddCss().AddHtml().AddJS();

        /// <summary>
        /// Creates an empty builder without any plugins being added.
        /// </summary>
        /// <returns>The builder that can be used for configuration</returns>
        public static MinifyBuilder Empty() => new();

    }

}
