using GenHTTP.Api.Infrastructure;

namespace GenHTTP.Api.Content.Websites
{

    /// <summary>
    /// Interface that should be implemented by all builders providing
    /// a theme instance.
    /// </summary>
    /// <typeparam name="T">The theme instance which will be generated by the builder</typeparam>
    /// <remarks>
    /// Allows to define common standards shared between all of our themes,
    /// making it therefore easier to switch between them. Currently there
    /// are no common, shared features.
    /// </remarks>
    public interface IThemeBuilder<out T> : IBuilder<T> where T : ITheme
    {
        

    }

}
