using System.Text;

namespace GenHTTP.Generators.MemoryView;

internal static class CodeEmitter
{
    private const string FieldName = "_value";

    private const string PropertyName = "Bytes";

    internal static string Emit(StructInfo info)
    {
        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"[global::System.Diagnostics.DebuggerDisplay(\"{{_debugView,nq}}\")]");
        sb.AppendLine($"public readonly partial struct {info.TypeName} : global::System.IEquatable<{info.TypeName}>");
        sb.AppendLine("{");

        const string indent = "    ";

        // ─────────────────────────────────────────────────────────────────────
        // Backing Storage
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Backing Storage");
        sb.AppendLine();

        sb.AppendLine($"{indent}private readonly global::System.ReadOnlyMemory<byte> {FieldName};");
        sb.AppendLine($"{indent}private readonly int _hash;");

        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Initialization
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Initialization");
        sb.AppendLine();

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public {info.TypeName}(global::System.ReadOnlyMemory<byte> value)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    {FieldName} = value;");
        sb.AppendLine($"{indent}    _hash = ComputeHash(value.Span);");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        sb.AppendLine($"{indent}public {info.TypeName}(string value)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var bytes = global::System.GC.AllocateUninitializedArray<byte>(value.Length);");
        sb.AppendLine();
        sb.AppendLine($"{indent}    for (var i = 0; i < value.Length; i++)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        bytes[i] = (byte)value[i];");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    {FieldName} = bytes;");
        sb.AppendLine($"{indent}    _hash = ComputeHash(bytes);");
        sb.AppendLine($"{indent}}}");

        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Accessors
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Accessors");
        sb.AppendLine();

        sb.AppendLine($"{indent}public global::System.ReadOnlyMemory<byte> {PropertyName} => {FieldName};");

        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Helpers
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Helpers");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // ASCII normalization
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}private static byte Normalize(byte value)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var lower = (byte)(value | 0x20);");
        sb.AppendLine();
        sb.AppendLine($"{indent}    return (uint)(lower - 'a') <= ('z' - 'a')");
        sb.AppendLine($"{indent}        ? lower");
        sb.AppendLine($"{indent}        : value;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Case-insensitive hash
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}private static int ComputeHash(global::System.ReadOnlySpan<byte> span)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    const uint Offset = 2166136261;");
        sb.AppendLine($"{indent}    const uint Prime = 16777619;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    uint hash = Offset ^ (uint)span.Length;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    foreach (var b in span)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        hash ^= Normalize(b);");
        sb.AppendLine($"{indent}        hash *= Prime;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    return (int)hash;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Case-insensitive memory comparison
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}private static bool EqualsIgnoreCase(global::System.ReadOnlySpan<byte> a, global::System.ReadOnlySpan<byte> b)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (a.Length != b.Length)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return false;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // Exact equality is by far the cheapest successful path.
        // SequenceEqual is vectorized by the runtime where supported.
        sb.AppendLine($"{indent}    if (a.SequenceEqual(b))");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return true;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // Only normalize when exact equality failed.
        sb.AppendLine($"{indent}    for (var i = 0; i < a.Length; i++)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        if (Normalize(a[i]) != Normalize(b[i]))");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            return false;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    return true;");
        sb.AppendLine($"{indent}}}");

        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Equality
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Equality");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Generated type == Generated type
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public bool Equals({info.TypeName} other)");
        sb.AppendLine($"{indent}{{");

        // The hash is computed using the same case-insensitive normalization
        // as the equality comparison.
        sb.AppendLine($"{indent}    if (_hash != other._hash)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        return false;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        sb.AppendLine($"{indent}    return EqualsIgnoreCase({FieldName}.Span, other.{FieldName}.Span);");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Generated type == ReadOnlyMemory<byte>
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public bool Equals(global::System.ReadOnlyMemory<byte> other)");
        sb.AppendLine($"{indent}    => EqualsIgnoreCase({FieldName}.Span, other.Span);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // object.Equals
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public override bool Equals(object? obj)");
        sb.AppendLine($"{indent}    => obj is {info.TypeName} other && Equals(other);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // GetHashCode
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public override int GetHashCode() => _hash;");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Generated type == Generated type
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public static bool operator ==({info.TypeName} left, {info.TypeName} right)");
        sb.AppendLine($"{indent}    => left.Equals(right);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Generated type != Generated type
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public static bool operator !=({info.TypeName} left, {info.TypeName} right)");
        sb.AppendLine($"{indent}    => !left.Equals(right);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Generated type == ReadOnlyMemory<byte>
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public static bool operator ==({info.TypeName} left, global::System.ReadOnlyMemory<byte> right)");
        sb.AppendLine($"{indent}    => left.Equals(right);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // Generated type != ReadOnlyMemory<byte>
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public static bool operator !=({info.TypeName} left, global::System.ReadOnlyMemory<byte> right)");
        sb.AppendLine($"{indent}    => !left.Equals(right);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // ReadOnlyMemory<byte> == Generated type
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public static bool operator ==(global::System.ReadOnlyMemory<byte> left, {info.TypeName} right)");
        sb.AppendLine($"{indent}    => right.Equals(left);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // ReadOnlyMemory<byte> != Generated type
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"{indent}public static bool operator !=(global::System.ReadOnlyMemory<byte> left, {info.TypeName} right)");
        sb.AppendLine($"{indent}    => !right.Equals(left);");
        sb.AppendLine();

        // ─────────────────────────────────────────────────────────────────────
        // String representation
        // ─────────────────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}public override string ToString()");
        sb.AppendLine($"{indent}    => global::System.Text.Encoding.ASCII.GetString({FieldName}.Span);");
        sb.AppendLine();

        sb.AppendLine($"{indent}private string _debugView => ToString();");

        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        sb.AppendLine("}");

        return sb.ToString();
    }
}
