using System.Text;

namespace GenHTTP.Generators.MemoryView;

internal static class CodeEmitter
{
    internal static string Emit(StructInfo info)
    {
        var sb = new StringBuilder(512);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        // DebuggerDisplay follows ToString: no point showing a value if there's no ToString.
        if (info.GenerateToString)
        {
            sb.AppendLine($"[global::System.Diagnostics.DebuggerDisplay(\"{{_debugView,nq}}\")]");
        }

        sb.AppendLine($"public readonly partial struct {info.TypeName} : global::System.IEquatable<{info.TypeName}>");
        sb.AppendLine("{");

        const string indent = "    ";

        // ── Backing Storage ──────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Backing Storage");
        sb.AppendLine();
        sb.AppendLine($"{indent}private readonly global::System.ReadOnlyMemory<byte> {info.FieldName};");
        sb.AppendLine($"{indent}private readonly int _hash;");
        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        // ── Initialization ───────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Initialization");
        sb.AppendLine();

        sb.AppendLine($"{indent}public {info.TypeName}(global::System.ReadOnlyMemory<byte> value)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    {info.FieldName} = value;");
        sb.AppendLine($"{indent}    var hash = new global::System.HashCode();");
        sb.AppendLine($"{indent}    foreach (var b in value.Span)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        hash.Add((uint)((b | 0x20) - 'a') <= 'z' - 'a' ? (byte)(b | 0x20) : b);");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}    _hash = hash.ToHashCode();");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        sb.AppendLine($"{indent}public {info.TypeName}(string value)");
        sb.AppendLine($"{indent}    : this(global::System.Text.Encoding.ASCII.GetBytes(value)) {{ }}");
        sb.AppendLine();

        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        // ── Get-/Setters ──────────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Get-/Setters");
        sb.AppendLine();
        sb.AppendLine($"{indent}public global::System.ReadOnlyMemory<byte> {info.PropertyName} => {info.FieldName};");
        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();

        // ── Equality ──────────────────────────────────────────────────────────

        sb.AppendLine($"{indent}#region Equality");
        sb.AppendLine();

        sb.AppendLine($"{indent}public bool Equals({info.TypeName} other)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    if (_hash != other._hash) return false;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    var a = {info.FieldName}.Span;");
        sb.AppendLine($"{indent}    var b = other.{info.FieldName}.Span;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    if (a.Length != b.Length) return false;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    for (int i = 0; i < a.Length; i++)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var ca = a[i];");
        sb.AppendLine($"{indent}        var cb = b[i];");
        sb.AppendLine();
        sb.AppendLine($"{indent}        if (ca == cb) continue;");
        sb.AppendLine();
        sb.AppendLine($"{indent}        if ((ca | 0x20) != (cb | 0x20)) return false;");
        sb.AppendLine($"{indent}        if ((uint)((ca | 0x20) - 'a') > 'z' - 'a') return false;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    return true;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        sb.AppendLine($"{indent}public override bool Equals(object? obj) => obj is {info.TypeName} other && Equals(other);");
        sb.AppendLine();
        sb.AppendLine($"{indent}public override int GetHashCode() => _hash;");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static bool operator ==({info.TypeName} left, {info.TypeName} right) => left.Equals(right);");
        sb.AppendLine($"{indent}public static bool operator !=({info.TypeName} left, {info.TypeName} right) => !left.Equals(right);");

        if (info.GenerateToString)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}public override string ToString() => global::System.Text.Encoding.ASCII.GetString({info.FieldName}.Span);");
            sb.AppendLine();
            sb.AppendLine($"{indent}private string _debugView => ToString();");
        }

        sb.AppendLine();
        sb.AppendLine($"{indent}#endregion");
        sb.AppendLine();
        sb.AppendLine("}");

        return sb.ToString();
    }
}
