using GenHTTP.Api.Protocol;

namespace GenHTTP.Api.Content.Services;

/// <summary>
/// Declares a response that may be generated by an operation of a service.
/// </summary>
/// <remarks>
/// Responses are usually derived from the signature of the method implementing
/// the operation. Declaring a successful response (2xx) on a method replaces the
/// derived responses, e.g. to announce that an operation responds with
/// <see cref="ResponseStatus.Created" /> instead of <see cref="ResponseStatus.Ok" />.
/// If no <see cref="Type" /> is given for such a response, the type returned by
/// the method will be used to describe the content.
///
/// Placed on a service class, the response applies to all operations of the
/// service which do not declare a response with the same status on their own,
/// which allows to document error responses in a single place.
///
/// Declaring multiple responses with the same status but different content
/// types will merge them into a single response.
/// </remarks>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface | AttributeTargets.Method, AllowMultiple = true)]
public sealed class ResponseAttribute : DocumentationAttribute
{

    #region Get-/Setters

    /// <summary>
    /// The status of the response.
    /// </summary>
    public ResponseStatus Status { get; }

    /// <summary>
    /// Describes the circumstances the response is generated in.
    /// </summary>
    public string? Description { get; }

    /// <summary>
    /// The type of the content sent with this response, if any.
    /// </summary>
    public Type? Type { get; set; }

    /// <summary>
    /// The content type of the response (e.g. "image/png"), if it is not
    /// determined by the serialization formats supported by the service.
    /// </summary>
    public string? ContentType { get; set; }

    #endregion

    #region Initialization

    /// <summary>
    /// Declares a response that may be generated by the annotated operation.
    /// </summary>
    /// <param name="status">The status of the response</param>
    /// <param name="description">Describes the circumstances the response is generated in</param>
    public ResponseAttribute(ResponseStatus status, string? description = null)
    {
        Status = status;
        Description = description;
    }

    #endregion

}
