<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <Description>Web server engine based on Microsoft Kestrel that can be used to develop applications using the GenHTTP development framework</Description>
        <PackageTags>GenHTTP HTTP Embedded Webserver Server Library C# Kestrel Engine</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>

    </PropertyGroup>

    <ItemGroup>

        <ProjectReference Include="..\..\API\GenHTTP.Api.csproj" />

        <ProjectReference Include="..\Shared\GenHTTP.Engine.Shared.csproj" />

        <ProjectReference Include="..\..\Modules\IO\GenHTTP.Modules.IO.csproj" />

        <ProjectReference Include="..\..\Modules\ErrorHandling\GenHTTP.Modules.ErrorHandling.csproj" />
        
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
