namespace GenHTTP.Api.Protocol;

// todo: re-visit

/// <summary>
/// Allows the response generated by a builder or handler to be
/// adjusted.
/// </summary>
/// <remarks>
/// This can be useful if you would like to add behavior that the
/// original handler (such as a page renderer) does not provide.
/// For example, as the page handlers implement this interface,
/// you can add a header to the response being generated for a page.
/// </remarks>
/// <typeparam name="TBuilder">The type of builder used as a return value</typeparam>
public interface IResponseModification<out TBuilder>
{

    /// <summary>
    /// Specifies the HTTP status code of the response.
    /// </summary>
    /// <param name="status">The HTTP status code of the response</param>
    TBuilder Status(ResponseStatus status);

    /// <summary>
    /// Specifies how the server should treat the connection after this response has been sent.
    /// </summary>
    /// <param name="handling">The mode to be applied</param>
    TBuilder Connection(Connection handling);

    /// <summary>
    /// Sets the given header field on the response. Changing HTTP
    /// protocol headers may cause incorrect behavior.
    /// </summary>
    /// <param name="key">The name of the header to be set</param>
    /// <param name="value">The value of the header field</param>
    TBuilder Header(string key, string value);

    /// <summary>
    /// Adds the given cookie to the response.
    /// </summary>
    /// <param name="cookie">The cookie to be added</param>
    TBuilder Cookie(Cookie cookie);

}
