using System;
using System.Collections.Generic;

using GenHTTP.Api.Protocol;

namespace GenHTTP.Modules.Reflection
{

    /// <summary>
    /// Configures the method provider which invokes functionality
    /// provided via reflection.
    /// </summary>
    public interface IMethodConfiguration
    {

        /// <summary>
        /// The HTTP verbs which are supported by this method.
        /// </summary>
        public HashSet<FlexibleRequestMethod> SupportedMethods { get; }

        /// <summary>
        /// If specified, the content generated by this method
        /// will not be declared and therefore not be listed
        /// in sitemaps or other content dependent functionality.
        /// </summary>
        public bool IgnoreContent { get; }

        /// <summary>
        /// If set, the given type will be instantiated when content
        /// is requested to discover the content which is available.
        /// </summary>
        /// <remarks>
        /// The specified type must implement interface <see cref="IContentHints"/>.
        /// </remarks>
        public Type? ContentHints { get; }

    }

}
