using GenHTTP.Api.Protocol;

namespace GenHTTP.Modules.Reflection;

/// <summary>
/// Attribute indicating that this method can be invoked
/// via reflection.
/// </summary>
[AttributeUsage(AttributeTargets.Method)]
public class MethodAttribute : Attribute, IMethodConfiguration
{

    #region Get-/Setters

    /// <summary>
    /// The HTTP verbs which are supported by this method.
    /// </summary>
    public HashSet<FlexibleRequestMethod> SupportedMethods { get; set; }

    /// <summary>
    /// If specified, the content generated by this method
    /// will not be declared and therefore not be listed
    /// in sitemaps or other content dependent functionality.
    /// </summary>
    public bool IgnoreContent { get; set; }

    #endregion

    #region Initialization

    /// <summary>
    /// Marks the method as a invokable function.
    /// </summary>
    public MethodAttribute()
    {
            SupportedMethods = new(2) {
                FlexibleRequestMethod.Get(RequestMethod.GET),
                FlexibleRequestMethod.Get(RequestMethod.HEAD)
            };
        }

    /// <summary>
    /// Marks the method as a invokable function for the specified HTTP verbs.
    /// </summary>
    /// <param name="methods">The HTTP verbs supported by this method</param>
    public MethodAttribute(params RequestMethod[] methods)
    {
            SupportedMethods = new(methods.Select(m => FlexibleRequestMethod.Get(m)));
        }

    /// <summary>
    /// Marks the method as a invokable function for the specified HTTP verbs.
    /// </summary>
    /// <param name="methods">The HTTP verbs supported by this method</param>
    public MethodAttribute(params FlexibleRequestMethod[] methods)
    {
            SupportedMethods = new(methods);
        }

    #endregion

}
