using GenHTTP.Api.Protocol;

namespace GenHTTP.Modules.Reflection;

/// <summary>
/// Ensures that a method collection is initialized exactly once, as this
/// might be a heavy task involving code generation. Also provides an
/// execution path that will not generate a state machine.
/// </summary>
public class SynchronizedMethodCollection(Func<IRequest, Task<MethodCollection>> factory)
{
    private MethodCollection? _instance;

    private Task<MethodCollection>? _initialization;

    #region State Handling

    /// <summary>
    /// Fetches the method collection to be used.
    /// </summary>
    /// <param name="request">The currently handled request</param>
    /// <returns>The method collection to be used</returns>
    public Task<MethodCollection> GetAsync(IRequest request)
    {
        if (_instance != null)
        {
            return Task.FromResult(_instance);
        }

        var init = _initialization;

        if (init != null)
        {
            return init;
        }

        init = InitializeAsync(request);

        var original = Interlocked.CompareExchange(ref _initialization, init, null);

        return original ?? init;
    }

    private async Task<MethodCollection> InitializeAsync(IRequest request)
    {
        var instance = await factory(request).ConfigureAwait(false);
        _instance = instance;
        return instance;
    }

    #endregion

    #region Request Handling

    /// <summary>
    /// Instructs the cached method collection to handle the given request.
    /// </summary>
    /// <param name="request">The request to be handled</param>
    /// <returns>The response generated by the method collection</returns>
    public ValueTask<IResponse?> HandleAsync(IRequest request)
        => _instance?.HandleAsync(request) ?? HandleWithInitialization(request);

    private async ValueTask<IResponse?> HandleWithInitialization(IRequest request)
        => await (await GetAsync(request)).HandleAsync(request);

    #endregion

}
